# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PDF PII Remover

on:
  push:
    branches: [ master ]
    tags:
      - v1.0.1
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: rihenperry/pdf_pii_remover
      
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      
    - name: Install pdftotext system libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpoppler-cpp-dev pkg-config python3-dev
        
    - name: mkdir output directory for pytest to run tests on transformed documents
      run: mkdir -p ~/pdf_pii_remover/output
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run pytest to verify PII are deleted from pdf documents
      run: |
        pytest -s -v
